### ISSUE TITLE
nn.Parameters is omitted

### ISSUE THREAD

**Issue by NehzUx** [TylerYep/torchinfo#54] opened 2021-06-08 09:09 UTC
Hi,

Torchinfo is not counting nn.Parameters into account now. Actually this whole layer is omitted.

E.g. self.layer = nn.Parameter(torch.FloatTensor(16, 64)) which contains 1024 parameters but Torchinfo doesn't add or show in the summary(model).

PyTorch version: 1.8.1
torchinfo version: 0.1.4

I think it is related to some extent #28 .

**Comment by TylerYep** [comment] 2021-06-11 05:26
Could you help me reproduce the error? Your code seems like it should work:

```
class CustomModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Parameter(torch.FloatTensor(16, 64))

    def forward(self, x):
        return self.layer

summary(model, input_size=(1,))
```

This code gives me:

```
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
CustomModule                             [16, 64]                  1,024
==========================================================================================
Total params: 1,024
Trainable params: 1,024
Non-trainable params: 0
Total mult-adds (M): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.01
==========================================================================================
```

**Comment by TylerYep** [comment] 2021-06-13 00:28
Closing since it looks like this is working fine now.

Added test case in https://github.com/TylerYep/torchinfo/commit/1737da35bb1b69bd18b2c180d6d54f367fd0de9c

**Closed by TylerYep** 2021-06-13 00:28 UTC
